In [1]:
import numpy as np



|              Copy.                            |                  View                                    |
|-----------------------------------------------| ---------------------------------------------------------|
|1. The copy is a new array                     |1. The view is just a view of the original array.         |
|2.The copy owns the data and any changes made to the copy will not affect original array and any changes made to the original array will not affect the copy.| 2. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## Make a copy, change the original array, and display both arrays:

### The copy SHOULD NOT be affected by the changes made to the original array.

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8])
# making a new copy of original array
x = arr1.copy()
arr1[1]=20

In [3]:
# array has been changed and this is our new copy
arr1

array([ 1, 20,  3,  4,  5,  6,  7,  8])

In [4]:
# the original array without any changes because we assigned the array to x before making copy
x

array([1, 2, 3, 4, 5, 6, 7, 8])

## Make a view, change the original array, and display both arrays:

### The view SHOULD be affected by the changes made to the original array.



In [5]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
# making a view of original array
y = arr2.view()
arr2[3]=30 

In [6]:
# original array has been changed and this is our view 
arr2

array([ 1,  2,  3, 30,  5,  6,  7,  8,  9])

In [7]:
# this is original array which also has been changed or affected.
y

array([ 1,  2,  3, 30,  5,  6,  7,  8,  9])

## Make a view, change the view, and display both arrays:

### The original array SHOULD be affected by the changes made to the view.

In [8]:
arr3 = np.array([1, 2, 3, 4, 5])
# making a view
z = arr3.view()
# making changes in view
z[0] = 50

In [9]:
arr3

array([50,  2,  3,  4,  5])

In [10]:
z

array([50,  2,  3,  4,  5])

## Check if Array Owns it's Data

Every NumPy array has the attribute base that returns ***None*** if the array owns the data.

because **copy** owns the data but **view** does not.

In [11]:
arr4 = np.array([1, 2, 3, 4, 5])

p = arr4.copy()
q = arr4.view()

In [12]:
print(p.base)

None


In [13]:
q.base

array([1, 2, 3, 4, 5])